name: build

on:
  push:
    branches: ["main", "master", "work"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config libssl-dev curl
      - name: Build Balance
        run: make -C tcp
      - name: Build Hitch
        run: |
          cd tls
          ./configure
          make
