name: build

on:
  push:
    branches: ["main", "master", "work"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - name: Build Balance
        run: make -C tcp
      - name: Build Docker image
        run: docker build -t hylance:ci .
